---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hfasset/hfaml_website/
    - export PHP=/opt/cpanel/ea-php85/root/usr/bin/php
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --working-dir=$DEPLOYPATH    
    - $PHP $DEPLOYPATH/artisan migrate --force
    - $PHP $DEPLOYPATH/artisan key:generate
    - $PHP $DEPLOYPATH/artisan config:clear
    - $PHP $DEPLOYPATH/artisan optimize:clear
    - $PHP $DEPLOYPATH/artisan cache:clear
    - $PHP $DEPLOYPATH/artisan view:clear
    - $PHP $DEPLOYPATH/artisan event:cache
    - $PHP $DEPLOYPATH/artisan view:cache
    - $PHP $DEPLOYPATH/artisan route:cache
    - $PHP $DEPLOYPATH/artisan config:cache
    - $PHP $DEPLOYPATH/artisan optimize